# Generated by Django 5.0.1 on 2024-02-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additions',
            field=models.IntegerField(default=0, verbose_name='additions to cart'),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='times liked'),
        ),
    ]
