# Generated by Django 5.0.1 on 2024-02-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_additions_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchases',
            field=models.IntegerField(default=0, verbose_name='times purchased'),
        ),
    ]
