# Generated by Django 5.0.1 on 2024-03-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_user_user_type_sitevisit_productvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvisit',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvisit',
            name='sitevisit_ptr',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_per_unit',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_measure',
            new_name='unit_measure',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='like',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='date_paid',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subcategories',
                to='shop.category',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='liked_by',
                to='shop.product',
            ),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='liked_products',
                to='shop.user',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd')], default='RUB', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product'),
        ),
        migrations.DeleteModel(
            name='ProductVisit',
        ),
        migrations.DeleteModel(
            name='SiteVisit',
        ),
    ]
