# Generated by Django 5.0.1 on 2024-03-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_redundant_fields_in_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='addition',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_product',
        ),
        migrations.DeleteModel(
            name='Addition',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
