# Generated by Django 5.0.1 on 2024-04-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_colour_product_sku_purchase_cancelled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. type of furniture, colour, size, etc.', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='confirmed',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='shipment',
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_address',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='ctg_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.categorytype'),
            preserve_default=False,
        ),
    ]
