# Generated by Django 5.0.1 on 2024-04-11 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_alter_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='date_added',
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateField(default=datetime.date.today, help_text='when first appeared in the catalog'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_production',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Defect',
        ),
    ]
