# Generated by Django 5.0.1 on 2024-04-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_as_individual_order_purchaser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchaser_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='orderdetail',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_order'),
        ),
    ]
