# Generated by Django 5.0.1 on 2024-04-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_shipment_address_order_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addition',
            old_name='ready_to_order',
            new_name='order_now',
        ),
    ]
