# Generated by Django 5.0.1 on 2024-04-19 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_shipment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='zip',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('user', 'address'), name='unique_user_address'),
        ),
    ]
