# Generated by Django 5.0.1 on 2024-05-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_like_product_rel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'value']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ctg_type',
            new_name='name',
        ),
    ]
