# Generated by Django 5.0.1 on 2024-05-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_model_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.ManyToManyField(to='shop.category'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
