# Generated by Django 5.0.1 on 2024-05-11 19:08

import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_cart_user_remove_order_shipment_cost_cart_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=models.SET(shop.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
