# Generated by Django 5.0.1 on 2024-03-18 09:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0011_collection_discount_remove_addition_quantity_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_measure', models.CharField(max_length=50)),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('owned', models.BooleanField(default=False)),
                ('components', models.ManyToManyField(to='production.component')),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('Produced', 'Produced'), ('Purchased', 'Purchased'), ('Found', 'Found')])),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery', models.DateTimeField(null=True)),
                ('actual_delivery', models.DateTimeField(null=True)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.component')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='production.supplier')),
            ],
        ),
    ]
