# Generated by Django 5.0.1 on 2024-03-19 16:04

import datetime
import django.db.models.deletion
import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('shop', '0012_product_colour_product_sku_purchase_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MaterialsUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.supplies')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=production.models.production_complete_date)),
                ('materials', models.ManyToManyField(through='production.MaterialsUsed', to='production.supplies')),
            ],
        ),
        migrations.AddField(
            model_name='materialsused',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production'),
        ),
        migrations.CreateModel(
            name='ProductsMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('complete', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='products',
            field=models.ManyToManyField(through='production.ProductsMade', to='shop.product'),
        ),
    ]
