# Generated by Django 5.0.1 on 2024-02-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_prod_card', '0002_mark_additions_mark_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
