# Generated by Django 5.0.1 on 2024-02-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_prod_card', '0003_delete_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0, verbose_name='times liked')),
                ('additions', models.IntegerField(default=0, verbose_name='additions to cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_prod_card.product')),
            ],
        ),
    ]
